apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "launchpad.fullname" . }}
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
data:
  LAUNCHPAD_PORT: {{ .Values.config.port | quote }}
  LAUNCHPAD_SESSION_TIMEOUT: {{ .Values.config.sessionTimeout | quote }}
  LAUNCHPAD_SESSION_CLEANUP_INTERVAL: {{ .Values.config.sessionCleanupInterval | quote }}
  LAUNCHPAD_POD_READY_TIMEOUT: {{ .Values.config.podReadyTimeout | quote }}
  LAUNCHPAD_VNC_SIDECAR_IMAGE: {{ .Values.config.vncSidecarImage | quote }}
  LAUNCHPAD_PRIMARY_COLOR: {{ .Values.branding.primaryColor | quote }}
  LAUNCHPAD_SECONDARY_COLOR: {{ .Values.branding.secondaryColor | quote }}
  LAUNCHPAD_TENANT_NAME: {{ .Values.branding.tenantName | quote }}
  {{- if .Values.branding.logoUrl }}
  LAUNCHPAD_LOGO_URL: {{ .Values.branding.logoUrl | quote }}
  {{- end }}
  {{- if ne .Values.secrets.provider "env" }}
  LAUNCHPAD_SECRETS_PROVIDER: {{ .Values.secrets.provider | quote }}
  {{- end }}
  {{- if eq .Values.secrets.provider "vault" }}
  {{- if .Values.secrets.vault.addr }}
  LAUNCHPAD_VAULT_ADDR: {{ .Values.secrets.vault.addr | quote }}
  {{- end }}
  {{- if .Values.secrets.vault.mountPath }}
  LAUNCHPAD_VAULT_MOUNT_PATH: {{ .Values.secrets.vault.mountPath | quote }}
  {{- end }}
  {{- if .Values.secrets.vault.namespace }}
  LAUNCHPAD_VAULT_NAMESPACE: {{ .Values.secrets.vault.namespace | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.secrets.provider "aws" }}
  {{- if .Values.secrets.aws.region }}
  LAUNCHPAD_AWS_REGION: {{ .Values.secrets.aws.region | quote }}
  {{- end }}
  {{- if .Values.secrets.aws.secretPrefix }}
  LAUNCHPAD_AWS_SECRET_PREFIX: {{ .Values.secrets.aws.secretPrefix | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.secrets.provider "kubernetes" }}
  {{- if .Values.secrets.kubernetes.secretName }}
  LAUNCHPAD_K8S_SECRET_NAME: {{ .Values.secrets.kubernetes.secretName | quote }}
  {{- end }}
  {{- if .Values.secrets.kubernetes.secretNamespace }}
  LAUNCHPAD_K8S_SECRET_NAMESPACE: {{ .Values.secrets.kubernetes.secretNamespace | quote }}
  {{- end }}
  {{- end }}
